higgsdecay: higgsdecay.cc
	g++ -I/home/faguicarv/software/pythia8317/include `root-config --cflags` $@.cc -o $@ -lpythia8 -L/home/faguicarv/software/pythia8317/lib `root-config --glibs`

tomography: tomography.cc
	g++ -I/home/faguicarv/software/pythia8317/include $@.cc -o $@ -lpythia8 -L/home/faguicarv/software/pythia8317/lib
